- RandomSamplingDataPointsFilter:
    prob: 0.1
- SurfaceNormalDataPointsFilter:
    knn: 10
    epsilon: 3.33
    keepNormals: 1
    keepDensities: 1
- MaxDensityDataPointsFilter:
     maxDensity: 100.0
- SimpleSensorNoiseDataPointsFilter:
    sensorType: 0
- ObservationDirectionDataPointsFilter
- OrientNormalsDataPointsFilter 
